name: geostatspy
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8
  - jupyterlab
  - matplotlib-base
  - pip
  - scipy
  - numpy
  - pandas
  - geopandas
  - nb_conda
  - ipywidgets
  - pip:
    - geostatspy
prefix: /home/andrew/anaconda3/envs/geostatspy
